### ISSUE TITLE
HomeSpawnPlus: Could not pass PlayerJoinEvent

### ISSUE THREAD

**Issue by AsyncChaka** [CriLisCraft/Issue-Tracker#23]
Stacktrace:

[18:02:34] [User Authenticator #1/INFO]: UUID of player Chaka is 00fa4033-421f-48d9-bc69-a0d9c9c4973e
[18:02:35] [Server thread/INFO]: [HomeSpawnPlus] Player Chaka changed names (oldName=Christophernjsp, uid=00fa4033-421f-48d9-bc69-a0d9c9c4973e)
[18:02:36] [Server thread/INFO]: Can not test connection as heartbeatsql is not set
[18:02:36] [Server thread/INFO]: Closing Connection[HomeSpawnPlus.1] psReuse[0] psCreate[4] psSize[4]
[18:02:36] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to HomeSpawnPlus v2.0-b610
org.bukkit.event.EventException
    at com.andune.minecraft.hsp.server.bukkit.BukkitEventDispatcher$1.execute(BukkitEventDispatcher.java:98) ~[?:?]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-c3c767f-33d5de3]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-c3c767f-33d5de3]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-c3c767f-33d5de3]
    at net.minecraft.server.v1_8_R1.PlayerList.onPlayerJoin(PlayerList.java:272) [spigot.jar:git-Spigot-c3c767f-33d5de3]
    at net.minecraft.server.v1_8_R1.PlayerList.a(PlayerList.java:156) [spigot.jar:git-Spigot-c3c767f-33d5de3]
    at net.minecraft.server.v1_8_R1.LoginListener.b(LoginListener.java:109) [spigot.jar:git-Spigot-c3c767f-33d5de3]
    at net.minecraft.server.v1_8_R1.LoginListener.c(LoginListener.java:41) [spigot.jar:git-Spigot-c3c767f-33d5de3]
    at net.minecraft.server.v1_8_R1.NetworkManager.a(NetworkManager.java:159) [spigot.jar:git-Spigot-c3c767f-33d5de3]
    at net.minecraft.server.v1_8_R1.ServerConnection.c(ServerConnection.java:82) [spigot.jar:git-Spigot-c3c767f-33d5de3]
    at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:800) [spigot.jar:git-Spigot-c3c767f-33d5de3]
    at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot.jar:git-Spigot-c3c767f-33d5de3]
    at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634) [spigot.jar:git-Spigot-c3c767f-33d5de3]
    at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537) [spigot.jar:git-Spigot-c3c767f-33d5de3]
    at java.lang.Thread.run(Thread.java:722) [?:1.7.0_07]
Caused by: javax.persistence.PersistenceException: ERROR executing DML bindLog[] error[[SQLITE_CONSTRAINT]  Abort due to constraint violation (column name is not unique)]
    at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.execute(DmlBeanPersister.java:116) ~[spigot.jar:git-Spigot-c3c767f-33d5de3]
    at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.update(DmlBeanPersister.java:85) ~[spigot.jar:git-Spigot-c3c767f-33d5de3]
    at com.avaje.ebeaninternal.server.persist.DefaultPersistExecute.executeUpdateBean(DefaultPersistExecute.java:110) ~[spigot.jar:git-Spigot-c3c767f-33d5de3]
    at com.avaje.ebeaninternal.server.core.PersistRequestBean.executeNow(PersistRequestBean.java:504) ~[spigot.jar:git-Spigot-c3c767f-33d5de3]
    at com.avaje.ebeaninternal.server.core.PersistRequestBean.executeOrQueue(PersistRequestBean.java:530) ~[spigot.jar:git-Spigot-c3c767f-33d5de3]
    at com.avaje.ebeaninternal.server.persist.DefaultPersister.update(DefaultPersister.java:436) ~[spigot.jar:git-Spigot-c3c767f-33d5de3]
    at com.avaje.ebeaninternal.server.persist.DefaultPersister.saveEnhanced(DefaultPersister.java:343) ~[spigot.jar:git-Spigot-c3c767f-33d5de3]
    at com.avaje.ebeaninternal.server.persist.DefaultPersister.saveRecurse(DefaultPersister.java:315) ~[spigot.jar:git-Spigot-c3c767f-33d5de3]
    at com.avaje.ebeaninternal.server.persist.DefaultPersister.save(DefaultPersister.java:282) ~[spigot.jar:git-Spigot-c3c767f-33d5de3]
    at com.avaje.ebeaninternal.server.core.DefaultServer.save(DefaultServer.java:1629) ~[spigot.jar:git-Spigot-c3c767f-33d5de3]
    at com.avaje.ebeaninternal.server.core.DefaultServer.save(DefaultServer.java:1619) ~[spigot.jar:git-Spigot-c3c767f-33d5de3]
    at com.andune.minecraft.hsp.storage.ebean.PlayerDAOEBean.savePlayer(PlayerDAOEBean.java:85) ~[?:?]
    at com.andune.minecraft.hsp.util.NameChangeUtil.changeName(NameChangeUtil.java:55) ~[?:?]
    at com.andune.minecraft.hsp.EventListener.playerJoin(EventListener.java:137) ~[?:?]
    at com.andune.minecraft.hsp.server.bukkit.BukkitEventDispatcher$1.execute(BukkitEventDispatcher.java:96) ~[?:?]
    ... 14 more
Caused by: java.sql.SQLException: [SQLITE_CONSTRAINT]  Abort due to constraint violation (column name is not unique)
    at org.sqlite.DB.newSQLException(DB.java:383) ~[spigot.jar:git-Spigot-c3c767f-33d5de3]
    at org.sqlite.DB.newSQLException(DB.java:387) ~[spigot.jar:git-Spigot-c3c767f-33d5de3]
    at org.sqlite.DB.execute(DB.java:342) ~[spigot.jar:git-Spigot-c3c767f-33d5de3]
    at org.sqlite.DB.executeUpdate(DB.java:363) ~[spigot.jar:git-Spigot-c3c767f-33d5de3]
    at org.sqlite.PrepStmt.executeUpdate(PrepStmt.java:85) ~[spigot.jar:git-Spigot-c3c767f-33d5de3]
    at com.avaje.ebeaninternal.server.lib.sql.ExtendedPreparedStatement.executeUpdate(ExtendedPreparedStatement.java:164) ~[spigot.jar:git-Spigot-c3c767f-33d5de3]
    at com.avaje.ebeaninternal.server.type.DataBind.executeUpdate(DataBind.java:74) ~[spigot.jar:git-Spigot-c3c767f-33d5de3]
    at com.avaje.ebeaninternal.server.persist.dml.UpdateHandler.execute(UpdateHandler.java:106) ~[spigot.jar:git-Spigot-c3c767f-33d5de3]
    at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.execute(DmlBeanPersister.java:105) ~[spigot.jar:git-Spigot-c3c767f-33d5de3]
    at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.update(DmlBeanPersister.java:85) ~[spigot.jar:git-Spigot-c3c767f-33d5de3]
    at com.avaje.ebeaninternal.server.persist.DefaultPersistExecute.executeUpdateBean(DefaultPersistExecute.java:110) ~[spigot.jar:git-Spigot-c3c767f-33d5de3]
    at com.avaje.ebeaninternal.server.core.PersistRequestBean.executeNow(PersistRequestBean.java:504) ~[spigot.jar:git-Spigot-c3c767f-33d5de3]
    at com.avaje.ebeaninternal.server.core.PersistRequestBean.executeOrQueue(PersistRequestBean.java:530) ~[spigot.jar:git-Spigot-c3c767f-33d5de3]
    at com.avaje.ebeaninternal.server.persist.DefaultPersister.update(DefaultPersister.java:436) ~[spigot.jar:git-Spigot-c3c767f-33d5de3]
    at com.avaje.ebeaninternal.server.persist.DefaultPersister.saveEnhanced(DefaultPersister.java:343) ~[spigot.jar:git-Spigot-c3c767f-33d5de3]
    at com.avaje.ebeaninternal.server.persist.DefaultPersister.saveRecurse(DefaultPersister.java:315) ~[spigot.jar:git-Spigot-c3c767f-33d5de3]
    at com.avaje.ebeaninternal.server.persist.DefaultPersister.save(DefaultPersister.java:282) ~[spigot.jar:git-Spigot-c3c767f-33d5de3]
    at com.avaje.ebeaninternal.server.core.DefaultServer.save(DefaultServer.java:1629) ~[spigot.jar:git-Spigot-c3c767f-33d5de3]
    at com.avaje.ebeaninternal.server.core.DefaultServer.save(DefaultServer.java:1619) ~[spigot.jar:git-Spigot-c3c767f-33d5de3]
    at com.andune.minecraft.hsp.storage.ebean.PlayerDAOEBean.savePlayer(PlayerDAOEBean.java:85) ~[?:?]
    at com.andune.minecraft.hsp.util.NameChangeUtil.changeName(NameChangeUtil.java:55) ~[?:?]
    at com.andune.minecraft.hsp.EventListener.playerJoin(EventListener.java:137) ~[?:?]
    at com.andune.minecraft.hsp.server.bukkit.BukkitEventDispatcher$1.execute(BukkitEventDispatcher.java:96) ~[?:?]
    ... 14 more
[18:02:36] [Server thread/INFO]: Chaka[/69.142.162.182:56635] logged in with entity id 305 at ([world] 153.72545524721693, 63.0, 99.29934607811148)

**Comment by AsyncChaka** [comment]
I have reported this to the plugin developer.  We are waiting for a reply
https://github.com/andune/HomeSpawnPlus/issues/61

**Comment by AsyncChaka** [comment]
Fixed
